services:
  api:
    image: ghcr.io/italia/developers-italia-api:v1.3.0
    env_file: ".env" # Must define PASETO_KEY
    environment:
      DATABASE_DSN: "host=db user=postgres password=postgres dbname=postgres port=5432"
      ENVIRONMENT: local
      GOFLAGS: -buildvcs=false
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/opt/app/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/publishers"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  crawler:
    image: italia/publiccode-crawler:0cdce559 # should match the version used in the build workflow
    depends_on:
      - api

    env_file: ".env" # Must define PASETO_KEY and GITHUB_TOKEN
    environment:
      - API_BASEURL=http://api:3000/v1/
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}

  client:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - API_BASEURL=http://localhost:3000/v1
    depends_on:
      - api
    ports:
      - "4321:8080"
volumes:
  pgdata:
